services:
  db:
    image: mariadb:11.4
    container_name: fingerprintweb-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fingerprintweb
      MYSQL_USER: fpw
      MYSQL_PASSWORD: fpwpass
    command:
      [
        "mariadbd",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "fpw",
          "-pfpwpass",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: dev
    container_name: fingerprintweb-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: mysql://fpw:fpwpass@db:3306/fingerprintweb
    volumes:
      - ../backend:/app
      - /app/node_modules
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: dev
    container_name: fingerprintweb-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000
    volumes:
      - ../frontend:/app
      - /app/node_modules

networks:
  default:
    name: fingerprintweb-net

volumes:
  db-data:
